### ISSUE TITLE
Set up read-only joining via IP and port

### ISSUE THREAD

**Issue by Andrei486** [Andrei486/uml-diagram-collab#7]
Allow users to join a host's room with read-only permissions (no changing permissions allowed) via the start page. Users should enter the IP and port in some format, probably in the same text box for later conversion to room code.
Once the connection is formed, the guest user should at least see the current state of the diagram; ideally we can get the host to send further updates as well.

To do:
- Make the message interpreter
- Create the new threads from somewhere
- Apply commands received from remote users

**Comment by em66850** [comment]
PR #40 added a direct connection dialog and the capability to parse the input (format is "ip:port"). It does not attempt to make a connection to the specified host.

**To do:**
Take the IP and port from the start screen controller and create a readonly connection to the host.

**Comment by Andrei486** [comment]
Leaving this here: JavaFX's method https://docs.oracle.com/javase/8/javafx/api/javafx/application/Platform.html#runLater-java.lang.Runnable- should allow us to execute Commands obtained via TCP on the UI thread without issues, as we receive them.

**Comment by Andrei486** [comment]
Now a duplicate of #56.
